// <auto-generated />
using MahasiswaAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MahasiswaAPI.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20211218140501_migrasi_database_pertama")]
    partial class migrasi_database_pertama
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MahasiswaAPI.Models.Mahasiswa", b =>
                {
                    b.Property<string>("Nobp")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JenisKelamin")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nohp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nobp");

                    b.ToTable("Tb_M_Mahasiswa");
                });
#pragma warning restore 612, 618
        }
    }
}
